const FS_CONFIG = {
    CLIENT_ID: '1UDBCOX4QA1GVLIF3NE4NG4OZRCI34YQD0ME2XN5GMDG1XHM',
    CLIENT_SECRET: '0R0DD0YOGGMEK4H0ATV3C0MUQCKJ5ULEBIPWOKDID5GFRGLV',
    BASE_URL: 'https://api.foursquare.com/v2/'
}

module.exports = FS_CONFIG;
